# <div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div> 

Exercise 1

|Term | Brief description |
|:--- | :---: |
|Subsetting|It is when you choose a portion of the list/array|
|Indexing |It is when you choose a specific element from a list/array using the element's index|
|Slicing |You cut out a portion of the list/array from a specific index to another|
|Masking|You apply a condition for each element in the list individually, to change its value or to remove those that do not satify the condition|

Exercise 2

In [7]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
numbers = np_array_2d[:, 0].astype(int)
remainder = numbers%2
count = remainder==1
odd_pair = np_array_2d[count] 
odd_letter = odd_pair[:, 1]
print(odd_letter)

['A' 'C' 'E' 'G' 'I']


In [11]:
#Exercise 3
import numpy as np
array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

less = array<50
less_int = -1*less.astype(int)
more = array>50
more_int = more.astype(int)
result = less_int + more_int
print(result)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
